import { Mail, MessageSquare, Phone, CheckSquare } from "lucide-react";
import { Link } from "react-router-dom";
import { cn } from "@/lib/utils";

interface Suggestion {
  icon: React.ElementType;
  title: string;
  description: string;
  action: string;
  href: string;
  variant: "default" | "warning" | "info";
}

export function SuggestedFollowUps() {
  // In a real implementation, these would be generated by an AI based on user's data
  const suggestions: Suggestion[] = [
    {
      icon: Mail,
      title: "Reply to important email",
      description: "You have 3 emails from key contacts waiting for responses",
      action: "View emails",
      href: "/mail?filter=unread",
      variant: "default",
    },
    {
      icon: Phone,
      title: "Return missed calls",
      description: "1 missed call from a contact you frequently reach out to",
      action: "View calls",
      href: "/phone",
      variant: "warning",
    },
    {
      icon: CheckSquare,
      title: "Complete overdue tasks",
      description: "2 tasks are past their due date and need attention",
      action: "View tasks",
      href: "/tasks?tab=overdue",
      variant: "warning",
    },
    {
      icon: MessageSquare,
      title: "Catch up on messages",
      description: "You have unread SMS messages from 2 conversations",
      action: "View messages",
      href: "/chat",
      variant: "info",
    },
  ];

  // Filter to show only the top 2-3 suggestions
  const topSuggestions = suggestions.slice(0, 3);

  if (topSuggestions.length === 0) {
    return null;
  }

  return (
    <div className="rounded-xl border border-border bg-card p-4 space-y-3">
      <h3 className="text-sm font-semibold text-foreground">Suggested follow-ups</h3>

      <div className="space-y-2">
        {topSuggestions.map((suggestion, idx) => {
          const Icon = suggestion.icon;
          return (
            <Link
              key={idx}
              to={suggestion.href}
              className={cn(
                "flex items-start gap-3 p-3 rounded-lg border transition-colors hover:bg-muted/50",
                suggestion.variant === "warning"
                  ? "border-amber-200 dark:border-amber-900/30 bg-amber-50 dark:bg-amber-950/20"
                  : suggestion.variant === "info"
                    ? "border-blue-200 dark:border-blue-900/30 bg-blue-50 dark:bg-blue-950/20"
                    : "border-border hover:border-primary/50",
              )}
            >
              <Icon
                size={16}
                className={cn(
                  "mt-0.5 shrink-0",
                  suggestion.variant === "warning"
                    ? "text-amber-600 dark:text-amber-400"
                    : suggestion.variant === "info"
                      ? "text-blue-600 dark:text-blue-400"
                      : "text-primary",
                )}
              />
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium text-foreground">{suggestion.title}</p>
                <p className="text-xs text-muted-foreground mt-0.5">
                  {suggestion.description}
                </p>
                <span className="text-xs text-primary font-medium mt-1 inline-block hover:underline">
                  {suggestion.action} →
                </span>
              </div>
            </Link>
          );
        })}
      </div>

      <p className="text-xs text-muted-foreground">
        🤖 Smart suggestions coming soon with AI-powered follow-up recommendations.
      </p>
    </div>
  );
}
